export const events = [
  {
    title: "Tech Innovation Summit",
    date: "March 25, 2025",
    location: "Silicon Valley, CA",
    desc: "A gathering of tech enthusiasts and innovators discussing the future of AI and blockchain.",
    image: "https://images.unsplash.com/photo-1699962699910-b2a5e9d44757?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "innovation",
  },
  {
    title: "Community Charity Drive",
    date: "April 10, 2025",
    location: "New York City, NY",
    desc: "Join us in giving back to the community through donations, volunteer work, and support programs.",
    image: "https://plus.unsplash.com/premium_photo-1683140538884-07fb31428ca6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Q29tbXVuaXR5JTIwQ2hhcml0eSUyMERyaXZlfGVufDB8fDB8fHww",
    category: "charity",
  },
  {
    title: "Yoga & Wellness Retreat",
    date: "May 5, 2025",
    location: "Bali, Indonesia",
    desc: "A week-long retreat focused on mental and physical well-being through yoga and meditation.",
    image: "https://images.unsplash.com/photo-1529693662653-9d480530a697?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8WW9nYSUyMCUyNiUyMFdlbGxuZXNzJTIwUmV0cmVhdHxlbnwwfHwwfHx8MA%3D%3D",
    category: "wellness",
  },
  {
    title: "Startup Networking Event",
    date: "June 15, 2025",
    location: "London, UK",
    desc: "Connect with investors, mentors, and fellow entrepreneurs to grow your startup.",
    image: "https://images.unsplash.com/photo-1559223607-a43c990c692c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3RhcnR1cCUyME5ldHdvcmtpbmclMjBFdmVudHxlbnwwfHwwfHx8MA%3D%3D",
    category: "workshops",
  },
  {
    title: "Holi Festival Celebration",
    date: "March 8, 2025",
    location: "Jaipur, India",
    desc: "Experience the vibrant festival of colors with music, dance, and traditional sweets.",
    image: "https://images.unsplash.com/photo-1674980629011-78230bdae029?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8SG9saSUyMEZlc3RpdmFsJTIwQ2VsZWJyYXRpb258ZW58MHx8MHx8fDA%3D",
    category: "festivals",
  },
  {
    title: "Youth Leadership Camp",
    date: "July 20, 2025",
    location: "Austin, TX",
    desc: "A summer camp designed to develop leadership skills among youth through interactive activities.",
    image: "https://images.unsplash.com/photo-1660794486044-ff1072c442f9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFlvdXRoJTIwTGVhZGVyc2hpcCUyMENhbXB8ZW58MHx8MHx8fDA%3D",
    category: "youth",
  },
  {
    title: "Annual Blood Donation Drive",
    date: "August 12, 2025",
    location: "Los Angeles, CA",
    desc: "Donate blood and help save lives. Free health check-ups available for all donors.",
    image: "https://plus.unsplash.com/premium_photo-1723044801280-fe1932fa9841?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8QW5udWFsJTIwQmxvb2QlMjBEb25hdGlvbiUyMERyaXZlfGVufDB8fDB8fHww",
    category: "charity",
  },
  {
    title: "Spiritual Awakening Workshop",
    date: "September 18, 2025",
    location: "Varanasi, India",
    desc: "A retreat focused on meditation, self-discovery, and spiritual enlightenment.",
    image: "https://images.unsplash.com/photo-1659439902271-8a310f0edeca?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3Bpcml0dWFsJTIwQXdha2VuaW5nJTIwV29ya3Nob3B8ZW58MHx8MHx8fDA%3D",
    category: "religious",
  },
  {
    title: "Corporate Social Responsibility Conference",
    date: "October 5, 2025",
    location: "Berlin, Germany",
    desc: "A forum for businesses to discuss sustainable and socially responsible business practices.",
    image: "https://images.unsplash.com/photo-1542744095-291d1f67b221?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "social",
  },
  {
    title: "Mental Health Awareness Seminar",
    date: "November 15, 2025",
    location: "Toronto, Canada",
    desc: "A seminar focusing on mental health education and breaking stigmas surrounding mental health issues.",
    image: "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "wellness",
  },
  {
    title: "Eid Celebration & Cultural Fest",
    date: "June 17, 2025",
    location: "Dubai, UAE",
    desc: "A grand celebration of Eid with cultural performances, food, and traditions.",
    image: "https://images.unsplash.com/photo-1521133573892-e44906baee46?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "religious",
  },
  {
    title: "AI & Machine Learning Workshop",
    date: "December 1, 2025",
    location: "San Francisco, CA",
    desc: "Hands-on training in AI and ML, covering deep learning, neural networks, and automation.",
    image: "https://images.unsplash.com/photo-1508921340878-ba53e1f016ec?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    category: "innovation",
  },
  {
    title: "Christmas Charity Gala",
    date: "December 20, 2025",
    location: "Paris, France",
    desc: "A fundraiser gala event supporting orphanages and underprivileged children.",
    image: "https://images.unsplash.com/photo-1645886702021-43a8849dedea?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fENocmlzdG1hcyUyMENoYXJpdHl8ZW58MHx8MHx8fDA%3D",
    category: "charity",
  },
];
export const categories = [
  "All",
  "religious",
  "social",
  "charity",
  "workshops",
  "festivals",
  "wellness",
  "youth",
  "innovation",
];
